### ISSUE TITLE
问题：在action里面 return (dispatch,getStore）这里的getStore是什么意思呢

### ISSUE THREAD

**Issue by Hanck97** [noiron/react-zhihu-daily#1]

**Comment by noiron** [comment]
这个是 `redux-thunk` 的写法，这里的 `actionCreator`  返回的是有两个参数的一个函数。`getStore` 实际上就是 `store` 的 `getState` 方法，这里只是用作参数的时候改了个名字。

> The inner function receives the store methods dispatch and getState as parameters.

具体可以看 [`redux-thunk` 的文档](https://github.com/gaearon/redux-thunk)。

**Comment by HancockTong** [comment]
好的，感谢！还有一个问题：
action里面为什么要写 记录主页当前的垂直位置setScrollTop呢

**Comment by HancockTong** [comment]
感谢！还有一个问题，container里main.js中 this.props.children children指的是什么呢
